### PR TITLE
fix(web): fix horizontal scrolling on WC modal

### LINKED ISSUE #4927: WalletConnect:list of the supported networks is displayed in one line that adds horizontal scroll to the modal window
## Bug description
WalletConnect:list of the supported networks is displayed in one line that adds horizontal scroll to the modal window 
## Environment

- Browser: FF
- Wallet: MetaMask/any
- Chain: Ethereum mainnet/any

## Steps to reproduce

1.  Go to safe
2. try to connect to the opensea using WC

## Expected result
The networks should be displayed in a few lines to hit the modal view size
## Screenshots

Image

### PR DESCRIPTION
**Pull request by valens-carpentier**
## What it solves
This PR fixes the horizontal scrolling issue in the Compatibility Warning modal when using WalletConnect.

Resolves #4927

## How this PR fixes it
- Adds `.chainContainer` element 
- Updates styles for `.chain` and `.origin` elements to ensure proper wrapping and spacing.

## How to test it
- Attempt to connect to OpenSea using WalletConnect on Sepolia.
- Open the console and copy an element that contains a chain (e.g. from the modal).
- Paste and duplicate it in the console to simulate a long list of chains.

## Screenshots
Screenshot 2025-04-14 at 16 42 04

## Checklist

- [ ] I've tested the branch on mobile (not applicable) 📱
- [ ] I've documented how it affects the analytics (not applicable) 📊
- [ ] I've written a unit/e2e test for it (not applicable) 🧑‍💻

### CODE REVIEW

File: apps/web/src/features/walletconnect/components/WcProposalForm/CompatibilityWarning.tsx [hunk 1]
```diff
@@ -30,7 +30,7 @@ export const CompatibilityWarning = ({
             Supported networks
           </Typography>
 
-          <Stack direction="row">
+          <Stack direction="row" flexWrap="wrap" justifyContent="center" className={css.chainContainer}>
```
Comment (katspaugh) [inline apps/web/src/features/walletconnect/components/WcProposalForm/CompatibilityWarning.tsx:33]: You could remove `flex-wrap: wrap` and `justify-content: center` as they are duplicated in the CSS class.

Also I would left-align them instead of center.

Comment (valens-carpentier) [reply apps/web/src/features/walletconnect/components/WcProposalForm/CompatibilityWarning.tsx]: Thanks. The changes have been implemented.

File: apps/web/src/features/walletconnect/components/WcProposalForm/styles.module.css [hunk 2]
```diff
@@ -10,7 +10,24 @@
...
+  white-space: nowrap;
+  display: inline-flex;
+  align-items: center;
+  justify-content: center;
+}
+
+.chainContainer {
+  display: flex;
+  flex-wrap: wrap;
+  justify-content: left-align;
```
Comment (katspaugh) [inline apps/web/src/features/walletconnect/components/WcProposalForm/styles.module.css:25]:
```suggestion
  justify-content: flex-start;
```

Please test that it works.

Comment (valens-carpentier) [reply apps/web/src/features/walletconnect/components/WcProposalForm/styles.module.css]: Screenshot 2025-04-15 at 12 00 11

This is the result with flex-start.
