### PR TITLE
fix(web): truncate long name tokens

### LINKED ISSUE #3438: Long token names cover the balance
## Environment
 - Browser: Chrome
 - Wallet: not connected
 - Chain: Gnosis chain but applies to any

## Steps to reproduce
 1. Find a Safe with tokens with long names (e.g. realty tokens like here https://app.safe.global/settings/setup?safe=gno:0x03f4156023e340779feda280185c251b6af00343)
 2. Go to the Assets page

## Expected result
Long names are truncated so the balances are visible

## Obtained result
Long names cover the balances and the layout looks buggy

## Screenshots

Image

### PR DESCRIPTION
**Pull request by valens-carpentier**
## What it solves
This PR fixes a bug where long token names overlap with the date display in the Queue and History views.

Resolves #3438

## How this PR fixes it
- Introduces MAX_TOKEN_SYMBOL_LENGTH to the TokenAmount component.
- Truncates token names on all pages where TokenAmount is used, preventing layout overflow.

## How to test it
- Find (or create) any Safe transactions in {Wallet} (eg. gno:0x03F4156023e340779Feda280185C251B6aF00343)
- Use the browser console to add a long token name (e.g., REALTOKEN-S-13041-HAYES-ST-DETROIT-MI).
- Verify that the long token name is truncated and does not overlap with the date.

## Screenshots
Screenshot 2025-04-07 at 16 24 38

## Checklist

- [ ] I've tested the branch on mobile 📱
- [ ] I've documented how it affects the analytics (not applicable) 📊
- [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: apps/web/src/components/common/TokenAmount/index.tsx [hunk 1]
```diff
@@ -28,16 +29,20 @@ const TokenAmount = ({
   const sign = direction === TransferDirection.OUTGOING ? '-' : ''
   const amount =
     decimals !== undefined ? formatVisualAmount(value, decimals, preciseAmount ? PRECISION : undefined) : value
+  
+  // Truncate token symbol if it's too long
+  const displayTokenSymbol = tokenSymbol ? ellipsis(tokenSymbol, MAX_TOKEN_SYMBOL_LENGTH) : undefined
```
Comment (katspaugh) [inline apps/web/src/components/common/TokenAmount/index.tsx:34]: Why do we need both a JS and a CSS ellipsis? CSS alone would be better.

Comment (valens-carpentier) [reply apps/web/src/components/common/TokenAmount/index.tsx:34]: You are right. I will keep CSS alone.

**Comment by valens-carpentier** [comment]
I have read the CLA Document and I hereby sign the CLA
