### PR TITLE
Fix: remove network selector from WC proposal warning

### LINKED ISSUE #4670: Multichain: switch network doesn't work in wallet connect flow if the user is trying to connect on unsupported network
## Bug description
Multichain: switch network doesn't work in walletconnection if the user is trying to connect on unsupported network

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet/ any

## Steps to reproduce
 1. Go to the safe on Sepolia
 2. try to connect opensea
Current result:  connect dialog with supported network and option to switch network appears, but it's not possible to use switch network 

## Expected result
Make sure that the user can switch to the right network in the WC dialog 
## Screenshots
image

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #4670

## How this PR fixes it

Screenshot 2025-01-07 at 14 18 45

### CODE REVIEW

File: apps/web/src/features/walletconnect/components/WcProposalForm/CompatibilityWarning.tsx [hunk 1]
```diff
@@ -21,11 +17,6 @@ export const CompatibilityWarning = ({
   const { safe } = useSafeInfo()
   const isUnsupportedChain = !chainIds.includes(safe.chainId)
   const { severity, message } = useCompatibilityWarning(proposal, isUnsupportedChain)
-  const peerUrl = proposal.params.proposer.metadata.url || proposal.verifyContext.verified.origin
-
-  const onChainChange = useCallback(() => {
-    trackEvent({ ...WALLETCONNECT_EVENTS.SWITCH_FROM_UNSUPPORTED_CHAIN, label: peerUrl })
```
Comment (usame-algan) [inline apps/web/src/features/walletconnect/components/WcProposalForm/CompatibilityWarning.tsx:27]: If this event is not used anywhere else I suggest to remove it.

**Review by usame-algan — APPROVED** [review]

**Comment by francovenica** [comment]
LGTM, same as the picture in the description
