### PR TITLE
Fix(Orgs): Show error when trying to add same safe to org

### LINKED ISSUE #5242: [Orgs]The same safe is displayed multiple times after "add safe" flow
## Bug description
The same safe is displayed multiple times after "add safe" flow
## Environment

- Browser: Chrome
- Wallet: MetaMask
- Chain: any

## Steps to reproduce

1.  Go to Safe accounts page
2. click Add Accounts
3. select safe 1 -> add accounts
4. check the table
5. open Add accounts again
6. click Add accounts button with the same safe selected

## Expected result
The same safe should not be re-added many times
## Obtained result
the same safe is added many times
## Screenshots

Image

Image

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #5242

## How this PR fixes it

- Shows an error and keeps the dialog open

## How to test it

1. Open an org
2. Add a safe account
3. Try to add the same safe account again
4. Observe an error message

## Screenshots
Screenshot 2025-03-18 at 14 25 10

## Checklist

- [ ] I've tested the branch on mobile 📱
- [ ] I've documented how it affects the analytics (if at all) 📊
- [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: apps/web/src/features/organizations/components/AddAccounts/index.tsx [hunk 1]
```diff
@@ -80,12 +82,14 @@ const AddAccounts = () => {
       })
 
       if (result.error) {
-        // TODO: Handle error message
+        // TODO: Add error handler and display more specific error
```
Comment (usame-algan) [inline apps/web/src/features/organizations/components/AddAccounts/index.tsx:85]: If there is time we can add a proper error handler but currently the types are not accurately working.

**Review by jmealy — APPROVED** [review]
