### PR TITLE
fix: improve truncation + add NFT fallbacks

### LINKED ISSUE #639: [Send NFT] Truncate NFT item name if it's too long for the name field on the Send NFT form
## Bug description
Truncate NFT item name if it's too long for the name field on the Send NFT form

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b/apps
 2. select ENS NFT item for sending 
Current result:
image

## Expected result
image

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #639 & #640

## How this PR fixes it

1. `MenuItem` truncation has been improved: truncation only occurs when the menu is not expanded.
2. Defaults have been added to "unknown" items: "Unknown collection" and "Unknown NFT"

Note: @francovenica, I do not have a Safe where the horizontal scrollbar appeared but I have added an `overflow` which should prevent this.

## How to test it

1. Open `rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b` and attempt to send an NFT (using impersonator.xyz if necessary). Observe the truncation only occuring on the closed menu.
2. Open `rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808` and attempt to send an NFT (using impersonator.xyz if necessary). Observe the fallback values.

## Screenshots

image
image

---

image
image

### CODE REVIEW

File: src/components/tx/modals/NftTransferModal/SendNftForm.tsx [hunk 1]
```diff
@@ -40,23 +40,16 @@ export type SendNftFormProps = {
 }
 
 const NftMenuItem = ({ image, name, description }: { image: string; name: string; description?: string }) => (
-  <Grid container spacing={1} alignItems="center" wrap="nowrap">
+  <Grid container spacing={1} alignItems="center" wrap="nowrap" overflow="hidden">
```
Comment (iamacook) [inline src/components/tx/modals/NftTransferModal/SendNftForm.tsx:43]: Prevent horizontal scrollbar on open menu.

File: src/components/tx/modals/NftTransferModal/SendNftForm.tsx [hunk 2]
```diff
@@ -40,23 +40,16 @@ export type SendNftFormProps = {
...
     <Grid item>
-      <Box width={20} height={20} overflow="hidden">
```
Comment (iamacook) [inline src/components/tx/modals/NftTransferModal/SendNftForm.tsx:45]: Was unnecessary.

File: src/components/tx/modals/NftTransferModal/SendNftForm.tsx [hunk 3]
```diff
@@ -40,23 +40,16 @@ export type SendNftFormProps = {
...
+      <Box width={20} height={20}>
         <ImageFallback src={image} fallbackSrc="/images/nft-placeholder.png" alt={name} height={20} />
       </Box>
     </Grid>
-    <Grid item>
+    <Grid item overflow="hidden">
```
Comment (iamacook) [inline src/components/tx/modals/NftTransferModal/SendNftForm.tsx:49]: Only truncate closed menu.

File: src/components/tx/modals/NftTransferModal/SendNftForm.tsx [hunk 4]
```diff
@@ -40,23 +40,16 @@ export type SendNftFormProps = {
...
       {description && (
-        <Typography
-          variant="caption"
-          color="primary.light"
-          display="block"
-          width="80%"
-          overflow="hidden"
-          textOverflow="ellipsis"
-        >
+        <Typography variant="caption" color="primary.light" display="block" overflow="hidden" textOverflow="ellipsis">
```
Comment (iamacook) [inline src/components/tx/modals/NftTransferModal/SendNftForm.tsx:52]: Only truncate closed menu.

**Review by usame-algan — APPROVED** [review]
👍

File: src/components/tx/modals/NftTransferModal/SendNftForm.tsx [hunk 5]
```diff
@@ -177,7 +170,7 @@ const SendNftForm = ({ params, onSubmit }: SendNftFormProps) => {
                     <MenuItem key={item.address + item.id} value={item.id}>
                       <NftMenuItem
                         image={item.imageUri || item.logoUri}
-                        name={item.name || item.tokenName}
+                        name={item.name || 'Unknown NFT'}
```
Comment (katspaugh) [inline src/components/tx/modals/NftTransferModal/SendNftForm.tsx:173]: Most of them don't have any name, only a tokenName. Please restore.
Also some might have a symbol but not a name, I would use that as a third fallback. Same for the collection name.

Comment (iamacook) [reply src/components/tx/modals/NftTransferModal/SendNftForm.tsx:173]: The `name` refers to the collection. Do you not think they should differ slightly? (will commit after we're sure):

- collections: `item.name || item.tokenSymbol || 'Unknown collection'`
- NFTs: `item.tokenName || item.name || item.tokenSymbol || 'Unknown NFT'`

Comment (katspaugh) [reply src/components/tx/modals/NftTransferModal/SendNftForm.tsx:173]: AFAIU, `name` refers to the name of the unique item, while `tokenName` is the name of the collection (they use the word token to refer to the contract).

Comment (katspaugh) [reply src/components/tx/modals/NftTransferModal/SendNftForm.tsx:173]: And this `name` field is almost always empty. Only a few collections have named items.

Comment (iamacook) [reply src/components/tx/modals/NftTransferModal/SendNftForm.tsx:173]: I've just looked over `safe-react` and it always uses `name` for both fields, falling back to an empty string. It would be nice to have a specific fallback though. Wdyt?

Comment (iamacook) [reply src/components/tx/modals/NftTransferModal/SendNftForm.tsx:173]: As per our discussion, we've settled for the following:

- Collections: `item.tokenName || item.tokenSymbol || 'Unknown collection'`
- NFTs: `item.name || (item.tokenName || item.tokenSymbol || '') + item.id`

File: src/components/tx/modals/NftTransferModal/SendNftForm.tsx [hunk 6]
```diff
@@ -177,7 +170,7 @@ const SendNftForm = ({ params, onSubmit }: SendNftFormProps) => {
                     <MenuItem key={item.address + item.id} value={item.id}>
                       <NftMenuItem
                         image={item.imageUri || item.logoUri}
-                        name={item.name || item.tokenName}
+                        name={item.name || (item.tokenName || item.tokenSymbol || '') + item.id}
```
Comment (katspaugh) [inline src/components/tx/modals/NftTransferModal/SendNftForm.tsx:173]: Looks good, but this will concat the id w/o any separator. It used to be `Bored Apes #14545`

File: src/components/tx/modals/NftTransferModal/SendNftForm.tsx [hunk 7]
```diff
@@ -177,7 +170,7 @@ const SendNftForm = ({ params, onSubmit }: SendNftFormProps) => {
                     <MenuItem key={item.address + item.id} value={item.id}>
                       <NftMenuItem
                         image={item.imageUri || item.logoUri}
-                        name={item.name || item.tokenName}
+                        name={item.name || `${item.tokenName || item.tokenSymbol || ''} #${item.id}`}
```
Comment (katspaugh) [inline src/components/tx/modals/NftTransferModal/SendNftForm.tsx:173]: This can potentially leave an empty space, but it should hopefully not happen in practice.

**Review by katspaugh — APPROVED** [review]

**Comment by francovenica** [comment]
Looks good. Like the images in the description.
The Unknown tokens now have a "default category"
The truncate looks good.
