### PR TITLE
Fix(Indexing status): poll every minute

### LINKED ISSUE #4784: Indexing status tooltip isn't updating
It's stuck at the same time until a page refresh.

image

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #4784

## How this PR fixes it

The indexing status was simply not polled at all. 😅

### CODE REVIEW

**Review by usame-algan — APPROVED** [review]

File: apps/web/src/components/sidebar/IndexingStatus/index.tsx [hunk 1]
```diff
@@ -4,16 +4,23 @@ import { getIndexingStatus } from '@safe-global/safe-gateway-typescript-sdk'
...
 import ExternalLink from '@/components/common/ExternalLink'
+import useIntervalCounter from '@/hooks/useIntervalCounter'
 
 const STATUS_PAGE = 'https://status.safe.global'
 const MAX_SYNC_DELAY = 1000 * 60 * 5 // 5 minutes
+const POLL_INTERVAL = 1000 * 60 // 1 minute
 
 const useIndexingStatus = () => {
   const chainId = useChainId()
+  const count = useIntervalCounter(POLL_INTERVAL)
```
Comment (usame-algan) [inline apps/web/src/components/sidebar/IndexingStatus/index.tsx:15]: This is causing excessive requests because the hook rerenders in the parent component and is not limited to `useIndexingStatus`

**Review by usame-algan — CHANGES_REQUESTED** [review]

File: apps/web/src/components/sidebar/IndexingStatus/index.tsx (hunk 1 above)
Comment (usame-algan) [reply apps/web/src/components/sidebar/IndexingStatus/index.tsx:15]: For context we ran into this issue before and the solution back then was to not use this hook but this is not a viable option here: https://github.com/safe-global/safe-wallet-monorepo/pull/4003#discussion_r1697155585

**Comment by liliya-soroka** [comment]
got rate limiting - the team is researching

**Review by usame-algan — APPROVED** [review]
Works now 👍

**Comment by liliya-soroka** [comment]
wrong information about "Synced 5 days ago for the Gnosis chain" in the tooltip
image
image

**Comment by liliya-soroka** [comment]
Verified. works
