### PR TITLE
Fix(Analytics): Remove GTM

### LINKED ISSUE #5159: [Analytics] Remove Google Tagmanager
## Overview

Tagmanager was introduced to handle more integrations other than GA. This has not happened. All events are sent to Tagmanager where they are mapped onto different GA properties. This adds additional complexity and another product that needs to be maintained.

## What must be done

- Remove `TagManager` initialization
- Move the mapping logic into the web frontend

## How to test it

- All events should still be tracked with the correct names and attributes
- The three different properties should still be used as before

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #5159

## How this PR fixes it

- Removes `TagManager` class and moves required logic into the gtm.ts file
- Adds `@next/third-parties` package
- Adds new `Analytics` component to initialize GA
- Replaces `dataLayer` calls with `sendGAEvent`

## ToDos

- [ ] Add env variables to CI

## How to test it

1. Ensure that the same events are still sent to GA
- Test this PR deployment vs. dev/staging/prod
- Do the same action in both deployments e.g. Create new transaction
- Compare `collect` network call data

2. Ensure events are still sent to the correct GA property
- Test property on localhost, dev, staging, PRs
- Prod property on prod
- Safe apps property when inside a safe app

## Checklist

- [ ] I've tested the branch on mobile 📱
- [ ] I've documented how it affects the analytics (if at all) 📊
- [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: apps/web/src/services/analytics/Analytics.tsx [hunk 1]
```diff
@@ -0,0 +1,23 @@
+import { GA_TRACKING_ID, IS_PRODUCTION, SAFE_APPS_GA_TRACKING_ID } from '@/config/constants'
+import { GoogleAnalytics } from '@next/third-parties/google'
+import { useEffect } from 'react'
+
+const Analytics = () => {
+  useEffect(() => {
+    // This needs to be added once in order for events with send_to: SAFE_APPS_GA_TRACKING_ID to work
+    window.gtag?.('config', SAFE_APPS_GA_TRACKING_ID, { debug_mode: !IS_PRODUCTION })
+
+    window.gtag?.('consent', 'default', {
```
Comment (katspaugh) [inline apps/web/src/services/analytics/Analytics.tsx:10]: We initialize it with these default settings and never change them. The previous implementation was upgrading them when a cookie consent is given (and we were also deleting cookies if the consent is withdrawn).

I think it's OK for the time being but it would be good to have a full feature parity with the previous implementation.

Comment (usame-algan) [reply apps/web/src/services/analytics/Analytics.tsx:10]: This is still being done inside the `useGtm` hook. All I did here is move the needed logic out of the `TagManager` to keep full parity

Comment (usame-algan) [reply apps/web/src/services/analytics/Analytics.tsx:10]: We should probably rename Gtm to Ga to make it more clear
