### PR TITLE
fix(web): rows per page setting disappears

### LINKED ISSUE #4307: "Rows per Page" Setting Disappears When Pagination 100 Rows in Address Book when Address <100
## Steps to reproduce
1. Navigate to https://safe.functionx.io/address-book?safe.
2. Change the pagination setting to display 100 rows per page.
3. Observe that the "Rows per page" setting disappears, preventing any further adjustments to the number of rows displayed.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: fxcore mainnet
 
## Obtained result
The "Rows per page" setting disappears after setting it to 100 rows per page.

## Expected result
The "Rows per page" setting should remain visible and functional, even after setting it to display 100 rows per page.

## Screenshots
https://drive.google.com/file/d/1WXNYcA0DwmlapFNW_dLwK-ERLxxK3XeE/view?usp=drive_link

### PR DESCRIPTION
**Pull request by valens-carpentier**
## What it solves
Fixes an issue where the "Rows per page" setting disappears in the Address Book when pagination is set to 100 rows and the total address count is fewer than 100.

Resolves #4307

## How this PR fixes it
- Changes condition to `rows.length > pageSizes[0] || rowsPerPage !== pageSizes[1])`

## How to test it
- Go to a Safe
- Import list of addresses with the import feature

## Screenshots
Uploading Screen Recording 2025-04-15 at 16.32.28.mov…

## Checklist

- [ ] I've tested the branch on mobile (not applicable) 📱
- [ ] I've documented how it affects the analytics (not applicable) 📊
- [ ] I've written a unit/e2e test for it (not applicable) 🧑‍💻

### CODE REVIEW

File: apps/web/src/components/common/EnhancedTable/index.tsx [hunk 1]
```diff
@@ -187,7 +187,7 @@ function EnhancedTable({ rows, headCells, mobileVariant }: EnhancedTableProps) {
         </Table>
       </TableContainer>
 
-      {rows.length > pagedRows.length && (
+      {(rows.length > pageSizes[0] || rowsPerPage !== pageSizes[1]) && (
```
Comment (iamacook) [inline apps/web/src/components/common/EnhancedTable/index.tsx:190]: Whilst this works, I think we could avoid relying on default values or array order with something like:

```suggestion
      {rows.length > rowsPerPage && (
```

Comment (katspaugh) [reply apps/web/src/components/common/EnhancedTable/index.tsx:190]: @iamacook your suggested code doesn't work, the pager disappears.

**Comment by katspaugh** [comment]
I've tested in a Safe with 800+ tokens and it works as expected now. Thanks @valens-carpentier! ✅

**Review by katspaugh — APPROVED** [review]
