### PR TITLE
Fix(Orgs): Fetch organizations when signed in

### LINKED ISSUE #4990: [Orgs] Integrate GET organization list endpoint
## Links

Epic on Notion: https://www.notion.so/safe-global/Org-onboarding-flow-1208180fe57380078591f5380a0c5d2a

## What must be done

- Fetch the organizations on the `OrgsList` view when the user is signed in and display organizations as cards

## How to test it

1. Go to `/welcome/organizations` and sign in
2. Create an org if necessary
3. Observe the org is showing up as a card

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #4990

## How this PR fixes it

- Uses the `useOrganizationsGetV1Query` RTK hook to fetch organizations when signed in
- Skips the fetch if the user is not signed in
- Displays result as cards

## How to test it

1. Go the `/welcome/organizations` and sign in
2. Observe your orgs showing up

## Screenshots

Screenshot 2025-02-14 at 11 49 10

## Checklist

- [ ] I've tested the branch on mobile 📱
- [ ] I've documented how it affects the analytics (if at all) 📊
- [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: apps/web/src/features/organizations/components/OrgsList/index.tsx [hunk 1]
```diff
@@ -71,23 +72,9 @@ const NoOrgsState = () => {
...
-  {
-    name: 'Optimism Foundation',
-    id: 2,
-    members: [{ id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }, { id: 6 }],
-    safes: [{ id: 1 }, { id: 4 }, { id: 7 }, { id: 8 }, { id: 9 }, { id: 10 }],
-  },
-]
-
 const OrgsList = () => {
   const isUserSignedIn = useAppSelector(isAuthenticated) // TODO: Implement logged in state once endpoint is ready
```
Comment (jmealy) [inline apps/web/src/features/organizations/components/OrgsList/index.tsx:76]: can we get rid of the comment?

**Review by jmealy — APPROVED** [review]
