### PR TITLE
fix: Handle timeout error in safe creation

### LINKED ISSUE #1291: There is no "Cancel", "retry" button when Code 800: Safe creation failed appears in console

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1291 

## How this PR fixes it

- Timeout errors thrown by ethers do not contain a `receipt` so we should handle it as an optional type

### Other changes

- Removes `receipt` from `TxEvent.PROCESSED` and `TxEvent.REVERTED` as it was not used

## How to test it

1. Create a new safe
2. Set the gas fee too low in your wallet and submit
3. Wait for 6.5 minutes OR reload the page and wait for 6.5 minutes
4. Observe a timeout error
5. Observe that the Cancel and Retry button is visible

## Screenshots
Screenshot 2022-11-30 at 18 19 13

### CODE REVIEW

File: src/hooks/useIsValidExecution.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ import ContractErrorCodes from '@/services/contracts/ContractErrorCodes'
 import { sameAddress } from '@/utils/addresses'
 
 const isContractError = <T extends EthersError>(error: T): error is T & { reason: keyof typeof ContractErrorCodes } => {
-  return Object.keys(ContractErrorCodes).includes(error.reason)
+  return Object.keys(ContractErrorCodes).includes(error.reason!)
```
Comment (usame-algan) [inline src/hooks/useIsValidExecution.ts:14]: I didn't bother with this as it will be removed with #1285

Comment (iamacook) [reply src/hooks/useIsValidExecution.ts:14]: I would suggest something along the lines of:

```ts
  const isEthersError = <T extends Error | EthersError>(error: T): error is EthersError
```

**Review by iamacook — COMMENTED** [review]
Appears to work well but there are failing tests.

File: src/hooks/useIsValidExecution.ts (hunk 1 above)
Comment (usame-algan) [reply src/hooks/useIsValidExecution.ts:14]: Why does the function need to handle `Error` and `EthersError` if it is only used in one place? I think we should rework `EthersError` in general. Ethers v6 will add [proper error types](https://github.com/ethers-io/ethers.js/issues/3565#issuecomment-1332668704) but for the time being I would suggest opting for a more simple solution e.g.

```
const isContractError = (error: EthersError) => {
  if (!error.reason) return false

  return Object.keys(ContractErrorCodes).includes(error.reason)
}
```

Comment (iamacook) [reply src/hooks/useIsValidExecution.ts]: The reasoning behind the union was because a standard error could be caught. Let's keep your solution and adjust the type as suggested in the future.

**Review by iamacook — APPROVED** [review]

**Comment by francovenica** [comment]
The error is there.
image
