### PR TITLE
fix(web): simplify multi token transfer dependencies

### LINKED ISSUE #5685: MassPayout: can not continue send tokens if the first recipient was deleted
## Bug description
MassPayout: can not continue send tokens if the first recipient was deleted
## Environment

- Browser: chrome
- Wallet: MetaMask
- Chain: any

## Steps to reproduce

1. Add the second recipient
2. Delete the first recipient
3. Click Next
Current result: Nothing happens

## Expected result
it should be possible to delete the first recipient and continue the process of sending funds

### PR DESCRIPTION
**Pull request by schmanu**
## What it solves

Resolves #5685 

## How this PR fixes it
- Clears up the dependencies avoiding triggering fields that were removed.

## How to test it
- Create a transfer with multiple recipients / tokens / amounts
- Remove the first transfer
- Witness that the total used amount is considered correctly and that the next button works.

## Checklist

- [x] I've tested the branch on mobile 📱
- [x] I've documented how it affects the analytics (if at all) 📊
- [x] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]

File: apps/web/src/components/tx-flow/flows/TokenTransfer/RecipientRow/index.tsx [hunk 1]
```diff
@@ -72,18 +72,11 @@ export const RecipientRow = ({ fieldArray, removable = true, remove, disableSpen
...
-        getFieldName(TokenTransferFields.amount, { name: MultiTokenTransferFields.recipients, index }),
-      ),
-    [recipients],
-  )
-
   const onRemove = useCallback(() => {
     remove?.(fieldArray.index)
-    trigger(deps)
-  }, [remove, fieldArray.index, trigger, deps])
+    clearErrors(MultiTokenTransferFields.recipients)
```
Comment (iamacook) [inline apps/web/src/components/tx-flow/flows/TokenTransfer/RecipientRow/index.tsx:77]: Nit: you don't need to call `clearErrors` before `trigger`.

Comment (schmanu) [reply apps/web/src/components/tx-flow/flows/TokenTransfer/RecipientRow/index.tsx]: Adjusted

**Review by iamacook — APPROVED** [review]
